spring.application.name=DemensApp
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/demens_app_DB
spring.datasource.username=root
spring.datasource.password=Ujr85gng.
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true